# Generated by Django 5.1.5 on 2025-02-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='empAddress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='empContact',
            field=models.BigIntegerField(),
        ),
    ]
