# Generated by Django 5.1.5 on 2025-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('marks', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
