# Generated by Django 5.1.5 on 2025-02-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_table_gov',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='test_table_it',
            old_name='Location',
            new_name='location',
        ),
    ]
